# Generated by Django 6.1 on 2026-08-28 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('programming', 'برنامه\u200cنویسی و توسعه نرم\u200cافزار'), ('personal_growth', 'توسعه فردی و مهارت\u200cهای نرم'), ('network_infrastructure', 'شبکه، امنیت و زیرساخت'), ('ai_data', 'هوش مصنوعی و علم داده'), ('design_product', 'طراحی محصول و تجربه کاربری'), ('devops_cloud', 'دواپس و رایانش ابری'), ('general_community', 'گفتگو و جامعه آزاد')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tweeter.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=15)),
                ('description', models.TextField()),
                ('stack_choice', models.CharField(blank=True, choices=[('backend_python', 'بک\u200cاند / پایتون (Django, FastAPI)'), ('backend_node', 'بک\u200cاند / Node.js'), ('backend_go_rust', 'بک\u200cاند / Go & Rust'), ('backend_java', 'بک\u200cاند / Java'), ('backend_csharp', 'بک\u200cاند / .NET C#'), ('backend_php', 'بک\u200cاند / PHP & Laravel'), ('frontend_react', 'فرانت\u200cاند / React & Next.js'), ('frontend_vue_angular', 'فرانت\u200cاند / Vue & Angular'), ('mobile_flutter_rn', 'توسعه موبایل (Flutter / React Native)'), ('mobile_native', 'توسعه موبایل نیتیو (Android Kotlin / iOS Swift)'), ('devops_sre', 'دواپس و مهندسی پایداری (DevOps / SRE / Docker / K8s)'), ('cloud_computing', 'رایانش ابری و زیرساخت (Cloud & Infrastructure)'), ('data_ai_ml', 'هوش مصنوعی و یادگیری ماشین (AI / Deep Learning / LLM)'), ('data_engineering', 'مهندسی و معماری داده (Data Engineering / Big Data)'), ('data_analysis', 'تحلیل داده و هوش تجاری (Data Analysis & BI)'), ('security_cyber', 'امنیت سایبری، شبکه و تست نفوذ (Cybersecurity)'), ('blockchain_web3', 'بلاکچین و وب۳ (Blockchain & Smart Contracts)'), ('game_development', 'توسعه بازی (Game Dev / Unity / Unreal)'), ('embedded_iot', 'سیستم\u200cهای نهفته و اینترنت اشیاء (Embedded / IoT / Hardware)'), ('qa_testing', 'تست و ارزیابی کیفیت نرم\u200cافزار (QA / Automation Testing)'), ('ui_ux_design', 'طراحی محصول، رابط و تجربه کاربری (UI/UX Design)'), ('product_management', 'مدیریت محصول و مالک محصول (Product Owner / PM)'), ('project_scrum', 'مدیریت چابک و اسکرام (Scrum / Agile Management)'), ('database_admin', 'مدیریت و بهینه\u200cسازی پایگاه داده (DBA / SQL & NoSQL)'), ('system_architect', 'معماری کلان سیستم و مایکروپروایدرها'), ('open_source', 'متن\u200cباز و مشارکت در گیت\u200cهاب (Open Source)'), ('psychology_growth', 'روانشناسی و شناخت فردی'), ('work_life_balance', 'تعادل کار و زندگی (پیشگیری از فرسودگی شغلی)'), ('mindfulness_focus', 'مایندفولنس، آرامش و تمرکز عمیق (Deep Work)'), ('productivity_habits', 'بهره\u200cوری، مدیریت زمان و ساخت عادات'), ('career_guidance', 'توسعه فردی، مصاحبه شغلی و منتورینگ'), ('tech_imposter', 'غلبه بر سندروم ایمپاستر و چالش\u200cهای سلامت روان فنی'), ('general_chat', 'گپ و گفت آزاد (Daily Talk)'), ('good_vibes', 'حال خوب و انرژی مثبت'), ('book_reading', 'معرفی و نقد کتاب'), ('podcast_media', 'پادکست، فیلم و محتوای شنیداری'), ('music_art', 'موسیقی، هنر و سرگرمی'), ('tech_meme_humor', 'میم، شوخی و طنز اکوسیستم'), ('question_answer', 'پرسش، پاسخ و تبادل نظر آزاد')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweeter.tweet')),
                ('retweet_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='tweeter.tweet')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='tweeter.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tweets/')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweeter.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tweeter.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tweets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tweet', 'user'), name='unique_tweet_like')],
            },
        ),
    ]
