# Generated by Django 6.1 on 2026-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='stack_choice',
            field=models.CharField(blank=True, choices=[('backend_python_dev', 'توسعه\u200cدهنده بک\u200cاند پایتون (Python / Django Developer)'), ('backend_node_dev', 'توسعه\u200cدهنده بک\u200cاند نود (Node.js Developer)'), ('backend_go_rust_dev', 'توسعه\u200cدهنده سیستم و بک\u200cاند (Go / Rust Developer)'), ('backend_java_dev', 'توسعه\u200cدهنده جاوا (Java Developer)'), ('backend_dotnet_dev', 'توسعه\u200cدهنده دات\u200cنت (.NET / C# Developer)'), ('backend_php_dev', 'توسعه\u200cدهنده پی\u200cاچ\u200cپی (PHP / Laravel Developer)'), ('frontend_react_dev', 'توسعه\u200cدهنده فرانت\u200cاند ری\u200cاکت (React / Next.js Developer)'), ('frontend_vue_angular_dev', 'توسعه\u200cدهنده فرانت\u200cاند (Vue / Angular Developer)'), ('mobile_cross_dev', 'برنامه\u200cنویس موبایل کراس\u200cپلتفرم (Flutter / React Native)'), ('mobile_native_dev', 'برنامه\u200cنویس موبایل نیتیو (Android / iOS Developer)'), ('devops_sre_eng', 'مهندس دواپس و پایداری (DevOps / SRE Engineer)'), ('cloud_eng', 'مهندس زیرساخت و ابری (Cloud Infrastructure Engineer)'), ('ai_ml_eng', 'متخصص هوش مصنوعی و یادگیری ماشین (AI / ML Engineer)'), ('data_eng', 'مهندس کلان\u200cداده و پایپ\u200cلاین (Data Engineer)'), ('data_analyst', 'تحلیل\u200cگر داده و هوش تجاری (Data Analyst / BI Specialist)'), ('security_pentester', 'متخصص امنیت سایبری و هکر قانونمند (Security Researcher / Pentester)'), ('blockchain_dev', 'توسعه\u200cدهنده بلاکچین و قراردادهای هوشمند (Blockchain / Web3 Developer)'), ('game_dev', 'توسعه\u200cدهنده بازی\u200cهای ویدیویی (Game Developer)'), ('embedded_iot_eng', 'مهندس امبدد و اینترنت اشیاء (Embedded & IoT Engineer)'), ('qa_automation_eng', 'مهندس تضمین کیفیت و تست خودکار (QA / Automation Engineer)'), ('ui_ux_designer', 'طراح رابط و تجربه کاربری (UI/UX Product Designer)'), ('product_manager', 'مدیر و مالک محصول (Product Manager / Owner)'), ('scrum_master_pm', 'مدیر پروژه چابک و اسکرام\u200cمستر (Scrum Master / Agile PM)'), ('dba_specialist', 'مدیر و متخصص پایگاه داده (Database Administrator / DBA)'), ('system_architect', 'معمار نرم\u200cافزار و سیستم\u200cهای توزیع\u200cشده (System Architect)'), ('open_source_contributor', 'مشارکت\u200cکننده فعال متن\u200cباز (Open Source Contributor)'), ('self_growth_explorer', 'کاوشگر رشد فردی و روانشناسی'), ('deep_worker', 'علاقه\u200cمند به کار عمیق و مایندفولنس (Deep Work Practitioner)'), ('productivity_enthusiast', 'خوره بهره\u200cوری و سیستم\u200cهای عادات'), ('mentor_advisor', 'راهنما و مشاور مسیر شغلی (Career Mentor)'), ('tech_burnout_survivor', 'دغدغه\u200cمند سلامت روان و غلبه بر فرسودگی'), ('casual_chatter', 'اهل گپ و گفت روزمره و گعده'), ('optimist_viber', 'انرژی\u200cبخش و مثبت\u200cاندیش'), ('book_worm', 'کتاب\u200cخوان و نقدکننده کتاب'), ('podcaster_critic', 'شنونده پادکست و نقدگر محتوا'), ('music_art_lover', 'دوست\u200cدار هنر و موسیقی'), ('tech_memer', 'خالق و علاقه\u200cمند به میم\u200cهای دنیای تک'), ('curious_asker', 'کنجکاو و پرسش\u200cگر جامعه')], max_length=50),
        ),
    ]
