# Generated by Django 6.1 on 2026-08-28 11:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('writer', 'Writer'), ('user', 'User')], default='user', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('stack_choice', models.CharField(blank=True, choices=[('backend_python', 'بک\u200cاند / پایتون (Django, FastAPI)'), ('backend_node', 'بک\u200cاند / Node.js'), ('backend_go_rust', 'بک\u200cاند / Go & Rust'), ('backend_java', 'بک\u200cاند / Java'), ('backend_csharp', 'بک\u200cاند / .NET C#'), ('backend_php', 'بک\u200cاند / PHP & Laravel'), ('frontend_react', 'فرانت\u200cاند / React & Next.js'), ('frontend_vue_angular', 'فرانت\u200cاند / Vue & Angular'), ('mobile_flutter_rn', 'توسعه موبایل (Flutter / React Native)'), ('mobile_native', 'توسعه موبایل نیتیو (Android Kotlin / iOS Swift)'), ('devops_sre', 'دواپس و مهندسی پایداری (DevOps / SRE / Docker / K8s)'), ('cloud_computing', 'رایانش ابری و زیرساخت (Cloud & Infrastructure)'), ('data_ai_ml', 'هوش مصنوعی و یادگیری ماشین (AI / Deep Learning / LLM)'), ('data_engineering', 'مهندسی و معماری داده (Data Engineering / Big Data)'), ('data_analysis', 'تحلیل داده و هوش تجاری (Data Analysis & BI)'), ('security_cyber', 'امنیت سایبری، شبکه و تست نفوذ (Cybersecurity)'), ('blockchain_web3', 'بلاکچین و وب۳ (Blockchain & Smart Contracts)'), ('game_development', 'توسعه بازی (Game Dev / Unity / Unreal)'), ('embedded_iot', 'سیستم\u200cهای نهفته و اینترنت اشیاء (Embedded / IoT / Hardware)'), ('qa_testing', 'تست و ارزیابی کیفیت نرم\u200cافزار (QA / Automation Testing)'), ('ui_ux_design', 'طراحی محصول، رابط و تجربه کاربری (UI/UX Design)'), ('product_management', 'مدیریت محصول و مالک محصول (Product Owner / PM)'), ('project_scrum', 'مدیریت چابک و اسکرام (Scrum / Agile Management)'), ('database_admin', 'مدیریت و بهینه\u200cسازی پایگاه داده (DBA / SQL & NoSQL)'), ('system_architect', 'معماری کلان سیستم و مایکروپروایدرها'), ('open_source', 'متن\u200cباز و مشارکت در گیت\u200cهاب (Open Source)'), ('psychology_growth', 'روانشناسی و شناخت فردی'), ('work_life_balance', 'تعادل کار و زندگی (پیشگیری از فرسودگی شغلی)'), ('mindfulness_focus', 'مایندفولنس، آرامش و تمرکز عمیق (Deep Work)'), ('productivity_habits', 'بهره\u200cوری، مدیریت زمان و ساخت عادات'), ('career_guidance', 'توسعه فردی، مصاحبه شغلی و منتورینگ'), ('tech_imposter', 'غلبه بر سندروم ایمپاستر و چالش\u200cهای سلامت روان فنی'), ('general_chat', 'گپ و گفت آزاد (Daily Talk)'), ('good_vibes', 'حال خوب و انرژی مثبت'), ('book_reading', 'معرفی و نقد کتاب'), ('podcast_media', 'پادکست، فیلم و محتوای شنیداری'), ('music_art', 'موسیقی، هنر و سرگرمی'), ('tech_meme_humor', 'میم، شوخی و طنز اکوسیستم'), ('question_answer', 'پرسش، پاسخ و تبادل نظر آزاد')], max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=150)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=150)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='used_invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='accounts.registrationcode'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.profile')),
            ],
        ),
    ]
