# Generated by Django 6.1 on 2026-08-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_workexperience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stack_choice',
            field=models.CharField(blank=True, choices=[('backend_python_dev', 'Python / Django Developer'), ('backend_node_dev', 'Node.js Developer'), ('backend_go_rust_dev', 'Go / Rust Developer'), ('backend_java_dev', 'Java Developer'), ('backend_dotnet_dev', '.NET / C# Developer'), ('backend_php_dev', 'PHP / Laravel Developer'), ('frontend_react_dev', 'React / Next.js Developer'), ('frontend_vue_angular_dev', 'Vue / Angular Developer'), ('mobile_cross_dev', 'Mobile Developer'), ('mobile_native_dev', 'Mobile Native Developer'), ('devops_sre_eng', 'DevOps / SRE Engineer'), ('cloud_eng', 'Cloud Infrastructure Engineer'), ('ai_ml_eng', 'AI / ML Engineer'), ('data_eng', 'Data Engineer'), ('data_analyst', 'Data Analyst / BI Specialist'), ('security_pentester', 'Security Researcher / Pentester'), ('blockchain_dev', 'Blockchain / Web3 Developer'), ('game_dev', 'Game Developer'), ('embedded_iot_eng', 'Embedded & IoT Engineer'), ('qa_automation_eng', 'QA / Automation Engineer'), ('ui_ux_designer', 'UI/UX Product Designer'), ('product_manager', 'Product Manager / Owner'), ('scrum_master_pm', 'Scrum Master / Agile PM'), ('dba_specialist', 'Database Administrator / DBA'), ('system_architect', 'System Architect'), ('open_source_contributor', 'Open Source Contributor'), ('self_growth_explorer', 'کاوشگر رشد فردی و روانشناسی'), ('deep_worker', 'Deep Work Practitioner'), ('productivity_enthusiast', 'خوره بهره\u200cوری و سیستم\u200cهای عادات'), ('mentor_advisor', 'راهنما و مشاور مسیر شغلی'), ('tech_burnout_survivor', 'دغدغه\u200cمند سلامت روان و غلبه بر فرسودگی'), ('optimist_viber', 'انرژی\u200cبخش و مثبت\u200cاندیش'), ('book_worm', 'کتاب\u200cخوان و نقدکننده کتاب'), ('podcaster_critic', 'شنونده پادکست و نقدگر محتوا'), ('music_art_lover', 'دوست\u200cدار هنر و موسیقی'), ('tech_memer', 'خالق و علاقه\u200cمند به میم\u200cهای دنیای تک'), ('curious_asker', 'کنجکاو و پرسش\u200cگر جامعه')], max_length=50),
        ),
    ]
